In [1]:
%reload_ext autoreload
%autoreload 2
import sys
sys.path.insert(0, "../")

In [2]:
# Env configs
from utils.librosa_cache import * 
enable_cache()

In [3]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

import librosa
from librosa.display import specshow
from tensorflow.keras import layers, models, losses

from utils.constants import *
from utils.read_audio import *

from layers.cqt import *
from layers.harmonic_stacking import *
from models.transcriber import *

In [4]:
# Load the data

data, sr = read_file("../data/song.mp3")
data

c:\Users\JOAQUIN DELA ROSA\anaconda3\envs\tfgpu\lib\site-packages\librosa\util\decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)


array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [16]:
input_data = np.array(data)
input_data.shape

(9661440,)

In [29]:
# Test if model works.
tf.config.run_functions_eagerly(True)
model = Transcriber([i for i in range(1, 8)])
model.compile(optimizer="adam", loss=losses.binary_crossentropy, run_eagerly=True)

In [31]:
model(input_data)

<tf.Tensor: shape=(1, 252, 18871, 7), dtype=float32, numpy=
array([[[[4.11131157e-04, 5.35047233e-01, 5.64900219e-01, ...,
          5.59645593e-01, 2.46259645e-01, 2.29309514e-01],
         [7.98508117e-04, 5.22839367e-01, 5.76051831e-01, ...,
          5.67786992e-01, 2.50845045e-01, 2.28353575e-01],
         [7.80851697e-04, 5.08685112e-01, 5.86913109e-01, ...,
          5.73150218e-01, 2.53588855e-01, 2.26790309e-01],
         ...,
         [4.23298798e-06, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [4.11527844e-06, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [4.01343823e-06, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00]],

        [[1.77128983e-04, 4.62389171e-01, 4.65670973e-01, ...,
          4.69662935e-01, 3.02293777e-01, 4.33449708e-02],
         [2.79542379e-04, 4.49169576e-01, 4.79034960e-01, ...,
       

In [8]:
model.summary()

Model: "transcriber"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
cqt (CQT)                    multiple                  0         
_________________________________________________________________
harmonic_stacking (HarmonicS multiple                  0 (unused)
_________________________________________________________________
dense (Dense)                multiple                  18872     
Total params: 18,872
Trainable params: 18,872
Non-trainable params: 0
_________________________________________________________________


In [9]:
purge_cache()